version: '3.2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    deploy:
      placement:
        constraints: [node.role == manager]  
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:      
      HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: ${NODEMANAGERIP}:2181
      KAFKA_CREATE_TOPICS: "ants:2:1:compact"
      KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=${NODEMANAGERIP} -Dcom.sun.management.jmxremote.rmi.port=1099"
      JMX_PORT: 1099
      KAFKA_HEAP_OPTS: "-Xmx256M -Xms128M"	  
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints: [node.role == manager] 
      #mode: global
  kafka-manager:
    image: sheepkiller/kafka-manager:latest
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: ${NODEMANAGERIP}:2181
      APPLICATION_SECRET: letmein
      KM_ARGS: -Djava.net.preferIPv4Stack=true	  
    deploy:
      placement:
        constraints: [node.role == manager] 